# Generated by Django 4.2.2 on 2023-06-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='prioroty',
            new_name='priority',
        ),
    ]
